# Generated by Django 4.0.5 on 2022-07-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='athor',
            new_name='author',
        ),
    ]
