# Generated by Django 4.0.6 on 2022-07-29 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='owner_of_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_of_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
